# Generated by Django 5.0 on 2023-12-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projetosas', '0002_professor_sala_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projetosas.aluno'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_projetosas.sala'),
        ),
    ]
