# Generated by Django 5.0 on 2023-12-10 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_projetosas', '0003_solicitacao_aluno_solicitacao_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='situacao',
            field=models.TextField(default='Em análise', max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_projetosas.sala'),
        ),
    ]
